#!/bin/bash
# This script downloads all the PDF files listed in the csv.

# Create the output directory if it doesn't exist
mkdir -p data-joyful

# Start of generated download commands
echo "Downloading 651289-i-am-not-a-cat.pdf..."
curl -L -o "data-joyful/651289-i-am-not-a-cat.pdf" "https://drive.google.com/uc?export=download&id=11TKn2LaBQyye0fYoEWzLS7Ac-gCL-VW7"
echo "Downloading 634390-i-would-have-liked-it-if.pdf..."
curl -L -o "data-joyful/634390-i-would-have-liked-it-if.pdf" "https://drive.google.com/uc?export=download&id=12zxyB4I15lis0RxwwyYg5FGWQEZvjx36"
echo "Downloading 641668-piku-and-his-magical-pishi.pdf..."
curl -L -o "data-joyful/641668-piku-and-his-magical-pishi.pdf" "https://drive.google.com/uc?export=download&id=14Cn2dPgPOS9MD73i42PPujIE_q5Dz16q"
echo "Downloading 517432-a-song-in-space-kesarbai-kerkar.pdf..."
curl -L -o "data-joyful/517432-a-song-in-space-kesarbai-kerkar.pdf" "https://drive.google.com/uc?export=download&id=17Ilc4NLG7t8yVjp3kfCuHO6N7SVr10aM"
echo "Downloading 609917-my-sister-and-me.pdf..."
curl -L -o "data-joyful/609917-my-sister-and-me.pdf" "https://drive.google.com/uc?export=download&id=18T7sjoTHANIBzyAQgrFMFm-HWwcBYVjt"
echo "Downloading 609979-exam-fever.pdf..."
curl -L -o "data-joyful/609979-exam-fever.pdf" "https://drive.google.com/uc?export=download&id=192mnAnt_JDr82rqA4nkL-8kOVGtEw1n_"
echo "Downloading 649059-dreaming-under-the-same-sky.pdf..."
curl -L -o "data-joyful/649059-dreaming-under-the-same-sky.pdf" "https://drive.google.com/uc?export=download&id=19LXod2PC0p6JRgPaKuARXCr38coaJPeO"
echo "Downloading 646796-little-tara-s-big-fire.pdf..."
curl -L -o "data-joyful/646796-little-tara-s-big-fire.pdf" "https://drive.google.com/uc?export=download&id=1A2hH7f0n8WwHxRwitlzK8tDyP318hMP2"
echo "Downloading 648754-a-home-made-of-books.pdf..."
curl -L -o "data-joyful/648754-a-home-made-of-books.pdf" "https://drive.google.com/uc?export=download&id=1C7WN_PVsOaTPaPZwCvJ9u8zkhYZCNrdP"
echo "Downloading 639210-nilu-and-zubeida.pdf..."
curl -L -o "data-joyful/639210-nilu-and-zubeida.pdf" "https://drive.google.com/uc?export=download&id=1DK2pN4KPxZM5dRnCMAm5UMn2_G-lhmBL"
echo "Downloading 632308-my-home.pdf..."
curl -L -o "data-joyful/632308-my-home.pdf" "https://drive.google.com/uc?export=download&id=1GKFt7kchY3d82Z8i0yA2e2W6wFifo12V"
echo "Downloading 593490-forgetful-dida.pdf..."
curl -L -o "data-joyful/593490-forgetful-dida.pdf" "https://drive.google.com/uc?export=download&id=1IanKiVxfLofB9ox51CU6L-WHbKEDO7Ik"
echo "Downloading 356934-who-got-the-goat.pdf..."
curl -L -o "data-joyful/356934-who-got-the-goat.pdf" "https://drive.google.com/uc?export=download&id=1IjIq5jQ63V_k3qBrXnE0h0sBY6N5Q6IT"
echo "Downloading 607066-when-the-sun-sets.pdf..."
curl -L -o "data-joyful/607066-when-the-sun-sets.pdf" "https://drive.google.com/uc?export=download&id=1IyhNiCJxRx-2juyBvoEXQ9wG8CoVtApM"
echo "Downloading 636905-this-land-is-my-school-dadaji-khobragade-the-rice-man-of-india.pdf..."
curl -L -o "data-joyful/636905-this-land-is-my-school-dadaji-khobragade-the-rice-man-of-india.pdf" "https://drive.google.com/uc?export=download&id=1JJtPdipOw8CGSAj67ian5KreZL3jW93x"
echo "Downloading 590649-my-yellow-umbrella.pdf..."
curl -L -o "data-joyful/590649-my-yellow-umbrella.pdf" "https://drive.google.com/uc?export=download&id=1KW10bPvi9NZAY1B1ijqjugZ6Ic015Z01"
echo "Downloading 621383-where-is-my-bat.pdf..."
curl -L -o "data-joyful/621383-where-is-my-bat.pdf" "https://drive.google.com/uc?export=download&id=1LwtRCOpho_gz4skNnDe4aU7X4eSN_h6-"
echo "Downloading 601765-it-s-not-fair.pdf..."
curl -L -o "data-joyful/601765-it-s-not-fair.pdf" "https://drive.google.com/uc?export=download&id=1NbXhprBquANFMqltxANy1EyzVM1O6EDm"
echo "Downloading 633629-chik-chik-girl.pdf..."
curl -L -o "data-joyful/633629-chik-chik-girl.pdf" "https://drive.google.com/uc?export=download&id=1OAgazuPKJ-VJHZZNN5kkGd3v8_pMUuGf"
echo "Downloading 642225-where-is-goggayya.pdf..."
curl -L -o "data-joyful/642225-where-is-goggayya.pdf" "https://drive.google.com/uc?export=download&id=1P1DVo5Ye3SI38e9emt8VwTWxalYCp4EY"
echo "Downloading 655300-this-is-how-i-draw.pdf..."
curl -L -o "data-joyful/655300-this-is-how-i-draw.pdf" "https://drive.google.com/uc?export=download&id=1Q63zUILez07HYXngVbk_AfZny8XlUsE-"
echo "Downloading 593495-sringeri-srinivas-keeps-his-promise.pdf..."
curl -L -o "data-joyful/593495-sringeri-srinivas-keeps-his-promise.pdf" "https://drive.google.com/uc?export=download&id=1QKjMw5qms7KYQRZr0f0k8oEejeu1s3v7"
echo "Downloading 609071-ajay-of-agumbe-and-the-signal-snake.pdf..."
curl -L -o "data-joyful/609071-ajay-of-agumbe-and-the-signal-snake.pdf" "https://drive.google.com/uc?export=download&id=1RTkNLeOSzJHghhOAyyGf0VvK8UBMSOBV"
echo "Downloading 609786-space-rules.pdf..."
curl -L -o "data-joyful/609786-space-rules.pdf" "https://drive.google.com/uc?export=download&id=1SPlZzOZj-CJb7CnCP4SDQ7uG_9LAU2RI"
echo "Downloading 577854-daddy-s-hobby.pdf..."
curl -L -o "data-joyful/577854-daddy-s-hobby.pdf" "https://drive.google.com/uc?export=download&id=1VX3uhDWe0i-CLyyGZy5Tj3UUppStgjL9"
echo "Downloading 362189-rajmohana-keloth-the-bug-finder-and-her-big-world-of-tiny-insects.pdf..."
curl -L -o "data-joyful/362189-rajmohana-keloth-the-bug-finder-and-her-big-world-of-tiny-insects.pdf" "https://drive.google.com/uc?export=download&id=1VcBOOJwsZh_T-IZeuuuG9WlEMU5hVmD_"
echo "Downloading 535775-come-back-soon-mira.pdf..."
curl -L -o "data-joyful/535775-come-back-soon-mira.pdf" "https://drive.google.com/uc?export=download&id=1YRNl8dzoi55PpADPRThUXrZhRxTcABhN"
echo "Downloading 612122-the-growing-up-book.pdf..."
curl -L -o "data-joyful/612122-the-growing-up-book.pdf" "https://drive.google.com/uc?export=download&id=1Yc5G29bdDrLcygIR3omx50JzUl_4T1N5"
echo "Downloading 556052-seasons.pdf..."
curl -L -o "data-joyful/556052-seasons.pdf" "https://drive.google.com/uc?export=download&id=1chXZKBDXpx-2eM5dJnzheFU3lJcUVuf7"
echo "Downloading 640032-what-i-want.pdf..."
curl -L -o "data-joyful/640032-what-i-want.pdf" "https://drive.google.com/uc?export=download&id=1dN-cmRX0Iv_yyChkaDGRINxcDd2q7514"
echo "Downloading 612553-muthu-and-kappu.pdf..."
curl -L -o "data-joyful/612553-muthu-and-kappu.pdf" "https://drive.google.com/uc?export=download&id=1eL70B2VdCx52amPvw06tGCXaBxvKnNRv"
echo "Downloading 638711-the-akkad-bakkad-cricket-song.pdf..."
curl -L -o "data-joyful/638711-the-akkad-bakkad-cricket-song.pdf" "https://drive.google.com/uc?export=download&id=1eM37G61UiF8sZvtsCAv64aqid0pi1IML"
echo "Downloading 453678-our-constitution-our-people.pdf..."
curl -L -o "data-joyful/453678-our-constitution-our-people.pdf" "https://drive.google.com/uc?export=download&id=1eprhkv-Xo4Doe4gYm5qjqd2mQdRmavB4"
echo "Downloading 650474-kabaddi-kabaddi.pdf..."
curl -L -o "data-joyful/650474-kabaddi-kabaddi.pdf" "https://drive.google.com/uc?export=download&id=1gpjek3IsyCeLY_RY1yyHY94GdDOVlIrM"
echo "Downloading 608413-full-of-light.pdf..."
curl -L -o "data-joyful/608413-full-of-light.pdf" "https://drive.google.com/uc?export=download&id=1iH6nnCNehUHC-V75IfkbIwk2XHEdvBtM"
echo "Downloading 598683-the-worst-best-friends.pdf..."
curl -L -o "data-joyful/598683-the-worst-best-friends.pdf" "https://drive.google.com/uc?export=download&id=1iHNJJscIpNOTpVLd4NJiOwX1X6q28_fn"
echo "Downloading 605451-moon-pizza.pdf..."
curl -L -o "data-joyful/605451-moon-pizza.pdf" "https://drive.google.com/uc?export=download&id=1irQfneOEvGWUu4C0eFR4CnEKB9HBPE-C"
echo "Downloading 650235-a-moon-full-of-ants.pdf..."
curl -L -o "data-joyful/650235-a-moon-full-of-ants.pdf" "https://drive.google.com/uc?export=download&id=1mRgPv3EzNDYSGr5PSZRNV41___WY6WWI"
echo "Downloading 632315-rain-rain.pdf..."
curl -L -o "data-joyful/632315-rain-rain.pdf" "https://drive.google.com/uc?export=download&id=1nRz9MLln6fVmaFFB9mVdxpRyuzwsOlZ6"
echo "Downloading 639952-champi-and-the-fig-tree.pdf..."
curl -L -o "data-joyful/639952-champi-and-the-fig-tree.pdf" "https://drive.google.com/uc?export=download&id=1niPPeiDrtwZ2wUkzyrPZQTzChYaUk0uT"
echo "Downloading 627427-pia-goes-to-chandni-chowk.pdf..."
curl -L -o "data-joyful/627427-pia-goes-to-chandni-chowk.pdf" "https://drive.google.com/uc?export=download&id=1p-8eb5QVV1FQ-5Kxd1Px7YnaiFCgT7rX"
echo "Downloading 608288-the-freedom-sisters.pdf..."
curl -L -o "data-joyful/608288-the-freedom-sisters.pdf" "https://drive.google.com/uc?export=download&id=1qRIvq_D9iBgSUrY6SuwT9mUu8dFzwunZ"
echo "Downloading 643377-bumbb-the-magical-cylinder.pdf..."
curl -L -o "data-joyful/643377-bumbb-the-magical-cylinder.pdf" "https://drive.google.com/uc?export=download&id=1rcpyAvvvVOqhltWvFoj4XyWlkCLR7SLU"
echo "Downloading 641131-the-rat-in-the-cat.pdf..."
curl -L -o "data-joyful/641131-the-rat-in-the-cat.pdf" "https://drive.google.com/uc?export=download&id=1sN9a7kwO7NNyRnhk7bAsUCglJAoH5Ad0"
echo "Downloading 643285-surki-and-tirki.pdf..."
curl -L -o "data-joyful/643285-surki-and-tirki.pdf" "https://drive.google.com/uc?export=download&id=1tbCSbGum1djZ5FeX3edyig31Qv-dg1KU"
echo "Downloading 632299-my-friends.pdf..."
curl -L -o "data-joyful/632299-my-friends.pdf" "https://drive.google.com/uc?export=download&id=1tmEsCH84HTOlegHS-WcoLEhjHZTyt72D"
echo "Downloading 594127-baba-in-a-sari.pdf..."
curl -L -o "data-joyful/594127-baba-in-a-sari.pdf" "https://drive.google.com/uc?export=download&id=1u4Kc_G4qgNRFC6syjvl4jW-YmACZNBUe"
echo "Downloading 606860-good-night-monu.pdf..."
curl -L -o "data-joyful/606860-good-night-monu.pdf" "https://drive.google.com/uc?export=download&id=1u8QKw0x5gX7sZ1GbkcAYGh40w0bHHyyo"
echo "Downloading 352163-paati-s-gold.pdf..."
curl -L -o "data-joyful/352163-paati-s-gold.pdf" "https://drive.google.com/uc?export=download&id=1v-NQSzKDVCc3eXy0FGLR97PFv7mgl9rh"
echo "Downloading 641028-there-you-are-a-spotting-book.pdf..."
curl -L -o "data-joyful/641028-there-you-are-a-spotting-book.pdf" "https://drive.google.com/uc?export=download&id=1wQXPtvGd9pYBQHcaVul7p9CSmL2_PJVo"
echo "Downloading 590264-we-are-making-a-book.pdf..."
curl -L -o "data-joyful/590264-we-are-making-a-book.pdf" "https://drive.google.com/uc?export=download&id=1wpQRoCB_-b6q3Rt1rEcwoRZoeKMM6j2Y"
echo "Downloading 561819-grace-one-engineer-s-fight-to-make-science-education-accessible-for-all.pdf..."
curl -L -o "data-joyful/561819-grace-one-engineer-s-fight-to-make-science-education-accessible-for-all.pdf" "https://drive.google.com/uc?export=download&id=1xWphMqgBXU53RQCbnJVhkOAs7OYRqh_0"
echo "Downloading 636218-aalepak-for-tatya.pdf..."
curl -L -o "data-joyful/636218-aalepak-for-tatya.pdf" "https://drive.google.com/uc?export=download&id=1yQsq7M1WaMxhu40Zfdz3v-ku6pyEyZYJ"
echo "Downloading 631095-thoithoi-feels-shy.pdf..."
curl -L -o "data-joyful/631095-thoithoi-feels-shy.pdf" "https://drive.google.com/uc?export=download&id=1zShHnT9AGemDasWyWtP-p-CctgoxwpUs"
echo "Downloading 361239-north-south-east-west.pdf..."
curl -L -o "data-joyful/361239-north-south-east-west.pdf" "https://drive.g supervisingoogle.com/uc?export=download&id=1zXfAKibn9S0jBrPLBTJed8yBJ918sjJZ"
echo "Downloading 374689-happy-as-a-hen.pdf..."
curl -L -o "data-joyful/374689-happy-as-a-hen.pdf" "https://drive.google.com/uc?export=download&id=18Z3W4n3qKh8GJIgF2YREK3130CpUBNma"
echo "Downloading 561474-an-adventure-for-puchku.pdf..."
curl -L -o "data-joyful/561474-an-adventure-for-puchku.pdf" "https://drive.google.com/uc?export=download&id=19dnB3cJQi9MLD1c9A0ii1Wg3cGyCI3H7"
echo "Downloading 539333-goal.pdf..."
curl -L -o "data-joyful/539333-goal.pdf" "https://drive.google.com/uc?export=download&id=1AF_KBPw7KVqPSvs7u_N3Km_AeO_vK5Aj"
echo "Downloading 608030-the-tortoiseshell-beetle.pdf..."
curl -L -o "data-joyful/608030-the-tortoiseshell-beetle.pdf" "https://drive.google.com/uc?export=download&id=1EuLLKQHRe33QT8YFO8-U7NEFBfENV_2z"
echo "Downloading 643469-the-pangolin-protectors.pdf..."
curl -L -o "data-joyful/643469-the-pangolin-protectors.pdf" "https://drive.google.com/uc?export=download&id=1a-gNjp06y_qqPMSWS-2OwKsbjVdrSg50"
echo "Downloading 540838-chasing-the-rain.pdf..."
curl -L -o "data-joyful/540838-chasing-the-rain.pdf" "https://drive.google.com/uc?export=download&id=1nZ_9vwkBNTQiymMA8wE1jh949S_cjWmC"

echo "All downloads finished." 